In [1]:
import numpy as np
import pandas as pd

country = ["India", "United States", "China", "Japan", "Germany", "United Kingdom", "France", "Italy", "Brazil", "Canada"]

pd.Series(country)

0             India
1     United States
2             China
3             Japan
4           Germany
5    United Kingdom
6            France
7             Italy
8            Brazil
9            Canada
dtype: object

In [2]:
runs = [100, 150, 20, 50, 00, 50, 40, 45, 50, 50]
pd.Series(runs)

0    100
1    150
2     20
3     50
4      0
5     50
6     40
7     45
8     50
9     50
dtype: int64

In [3]:
mark = [100, 150, 20, 50, 00, 50, 40, 45, 50, 50]
subject = ["Maths", "Science", "English", "History", "Geography", "Computer Science", "Physical Education", "Art", "Music", "Economics"]
pd.Series(mark, subject,name = "yashdeep")

Maths                 100
Science               150
English                20
History                50
Geography               0
Computer Science       50
Physical Education     40
Art                    45
Music                  50
Economics              50
Name: yashdeep, dtype: int64

In [4]:
marks = {"Maths": 100, "Science": 150, "English": 20, "History": 50, "Geography": 0, "Computer Science": 50, "Physical Education": 40, "Art": 45, "Music": 50, "Economics": 50}

marks = pd.Series(marks, name = "yashdeep")
print(marks)
marks.size

Maths                 100
Science               150
English                20
History                50
Geography               0
Computer Science       50
Physical Education     40
Art                    45
Music                  50
Economics              50
Name: yashdeep, dtype: int64

10

In [5]:
a = [1, 2, 3, 4, 5,7,45,6,77]

pd.Series(a).size

9

In [6]:
marks.isnull()

Maths                 False
Science               False
English               False
History               False
Geography             False
Computer Science      False
Physical Education    False
Art                   False
Music                 False
Economics             False
Name: yashdeep, dtype: bool

In [7]:
sub = pd.read_csv('E:\Pandas\Titanic.csv\Titanic-Dataset.csv',index_col = "PassengerId")
print(sub.head())
print(sub.tail())
print(sub.sample(5))

             Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0

             SibSp  Parch            Ticket     Fare Cabin Embarked
PassengerId
1                1      0         A/5 21171   7.2500   NaN        S
2                1      0          PC 17599  71.2833   C85        C
3                0      0  STON/O2. 3101282   7.9250   NaN        S
4                1      0            113803  53.1000  C123        S
5                0      0            373450   8.0500   NaN        S
             Survived  Pclass                                      Name  \
PassengerId
887                 0       2                     Montvila, Rev. Juozas
888                 1       1              Graham, Miss. Margaret Edith
889                 0       3  Johnston, Miss. Catherine Helen "Carrie"
890                 1       1                     Behr, Mr. Karl Howell
891                 0       3                       Dooley, Mr. Patrick

                Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
PassengerId
887            male  27.0      0      0      211536  13.00   NaN        S
888          female  19.0      0      0      112053  30.00   B42        S
889          female   NaN      1      2  W./C. 6607  23.45   NaN        S
890            male  26.0      0      0      111369  30.00  C148        C
891            male  32.0      0      0      370376   7.75   NaN        Q
             Survived  Pclass                     Name     Sex   Age  SibSp  \
PassengerId
644                 1       3          Foo, Mr. Choong    male   NaN      0
76                  0       3  Moen, Mr. Sigurd Hansen    male  25.0      0
413                 1       1   Minahan, Miss. Daisy E  female  33.0      1
501                 0       3         Calic, Mr. Petar    male  17.0      0
139                 0       3      Osen, Mr. Olaf Elon    male  16.0      0

             Parch  Ticket     Fare  Cabin Embarked
PassengerId
644              0    1601  56.4958    NaN        S
76               0  348123   7.6500  F G73        S
413              0   19928  90.0000    C78        Q
501              0  315086   8.6625    NaN        S
139              0    7534   9.2167    NaN        S

In [8]:
sub.sort_values(by="Ticket", ascending=True)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
505,1,1,"Maioni, Miss. Roberta",female,16.0,0,0,110152,86.500,B79,S
258,1,1,"Cherry, Miss. Gladys",female,30.0,0,0,110152,86.500,B77,S
760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0,0,110152,86.500,B77,S
263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.650,E67,S
559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.0,1,1,110413,79.650,E67,S
...,...,...,...,...,...,...,...,...,...,...,...
236,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,W./C. 6609,7.550,NaN,S
93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.175,E31,S
220,0,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,NaN,S
541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.000,B22,S
746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.000,B22,S

In [19]:
sub.sort_index(ascending=True)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
sub["Ticket"].value_counts()

Ticket
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64